package uno.d1s.springcloudsampleconfigserver.configuration

import org.springframework.cloud.config.server.EnableConfigServer
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigServer
class ConfigServerConfiguration