spring:
  application:
    name: spring-cloud-sample-zuul-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  routes:
    spring-cloud-sample-service-one: /serviceone/**
    spring-cloud-sample-service-two: /servicetwo/**