package uno.d1s.springcloudsamplezuulservice.configuration

import org.springframework.cloud.netflix.eureka.EnableEurekaClient
import org.springframework.context.annotation.Configuration

@Configuration
@EnableEurekaClient
class EurekaConfigurationO