spring:
  application:
    name: spring-cloud-sample-service-two

server:
  port: 0 # Random port number.

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}